export const shortletData = [
	{
		id: 1,
		image: "/gallery/gallery-thum-01.jpg",
		title: "Modern Apartment in City Center",
		location: "123 Urban Street, Downtown",
		price: "₦1,250,000",
		beds: 3,
		baths: 2,
		area: "1,200 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 2,
		image: "/gallery/gallery-thum-02.jpg",
		title: "Luxury Villa with Ocean View",
		location: "456 Coastal Road, Beachside",
		price: "₦2,500,000",
		beds: 5,
		baths: 4,
		area: "3,500 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 3,
		image: "/gallery/gallery-thum-03.jpg",
		title: "Cozy Studio in Historic District",
		location: "789 Heritage Lane, Old Town",
		price: "₦950/Night",
		beds: 1,
		baths: 1,
		area: "650 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 4,
		image: "/gallery/gallery-thum-04.jpg",
		title: "Family Home with Garden",
		location: "101 Suburban Drive, Green Valley",
		price: "₦1,750,000",
		beds: 4,
		baths: 3,
		area: "2,200 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 5,
		image: "/gallery/gallery-thum-05.jpg",
		title: "Penthouse with City Skyline View",
		location: "202 High Rise Avenue, Uptown",
		price: "₦3,200,000",
		beds: 3,
		baths: 3,
		area: "2,800 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-02.jpg",
			"/gallery/gallery-thum-03.jpg",
			"/gallery/gallery-thum-04.jpg",
			"/gallery/gallery-thum-05.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-07.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-08.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-09.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-10.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-11.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-12.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-13.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-14.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-15.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-16.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-17.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-18.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "₦1,450/Night",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
		detailImages: [
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
			"/gallery/gallery-thum-01.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
];
