export const properties = [
	{
		id: 1,
		image: "/gallery/gallery-thum-01.jpg",
		title: "Modern Apartment in City Center",
		location: "123 Urban Street, Downtown",
		price: "$1,250,000",
		beds: 3,
		baths: 2,
		area: "1,200 sqft",
		type: "For Sale",
	},
	{
		id: 2,
		image: "/gallery/gallery-thum-02.jpg",
		title: "Luxury Villa with Ocean View",
		location: "456 Coastal Road, Beachside",
		price: "$2,500,000",
		beds: 5,
		baths: 4,
		area: "3,500 sqft",
		type: "For Sale",
	},
	{
		id: 3,
		image: "/gallery/gallery-thum-03.jpg",
		title: "Cozy Studio in Historic District",
		location: "789 Heritage Lane, Old Town",
		price: "$950/month",
		beds: 1,
		baths: 1,
		area: "650 sqft",
		type: "For Rent",
	},
	{
		id: 4,
		image: "/gallery/gallery-thum-04.jpg",
		title: "Family Home with Garden",
		location: "101 Suburban Drive, Green Valley",
		price: "$1,750,000",
		beds: 4,
		baths: 3,
		area: "2,200 sqft",
		type: "For Sale",
	},
	{
		id: 5,
		image: "/gallery/gallery-thum-05.jpg",
		title: "Penthouse with City Skyline View",
		location: "202 High Rise Avenue, Uptown",
		price: "$3,200,000",
		beds: 3,
		baths: 3,
		area: "2,800 sqft",
		type: "For Sale",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-07.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-08.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-09.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-10.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-11.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-12.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-13.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-14.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-15.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-16.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-17.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-18.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside",
		price: "$1,450/month",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Rent",
	},
];
