export const properties = [
	{
		id: 1,
		image: "/gallery/gallery-thum-01.jpg",
		alt: "Modern apartment in Abuja city center with luxury interiors",
		title: "Modern Apartment in City Center",
		location: "123 Urban Street, Abuja",
		buildYear: "2024",
		structureType: "Brick",
		garageSize: 3,
		price: "₦1,250,000",
		beds: 3,
		baths: 2,
		area: "1,200 sqft",
		type: "For Sale",
		amenities: [
			"Air Conditioner",
			"Swimming pools",
			"Sport facilities",
			"Landscaped Gardens",
			"Surveillance Cameras",
			"Wide-Open Space",
			"Parks",
			"Gym",
			"Billiard table",
			"Package locker",
			"CLubhouse",
		],
		detailImages: [
			"/gallery/gallery-01.jpg",
			"/gallery/gallery-02.jpg",
			"/gallery/gallery-03.jpg",
			"/gallery/gallery-04.jpg",
			"/gallery/gallery-05.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 2,
		image: "/gallery/gallery-thum-02.jpg",
		alt: "Luxury villa with ocean view in Lekki, featuring private pool and garden",
		title: "Luxury Villa with Ocean View",
		location: "456 Coastal Road, Lekki",
		price: "₦2,500,000",
		beds: 5,
		baths: 4,
		area: "3,500 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-06.jpg",
			"/gallery/gallery-07.jpg",
			"/gallery/gallery-08.jpg",
			"/gallery/gallery-09.jpg",
			"/gallery/gallery-10.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 3,
		image: "/gallery/gallery-thum-03.jpg",
		alt: "Cozy studio apartment in historic Old Town with rustic charm",
		title: "Cozy Studio in Historic District",
		location: "789 Heritage Lane, Old Town, Ikoyi",
		price: "₦950,000",
		beds: 1,
		baths: 1,
		area: "650 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-11.jpg",
			"/gallery/gallery-12.jpg",
			"/gallery/gallery-13.jpg",
			"/gallery/gallery-14.jpg",
			"/gallery/gallery-15.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 4,
		image: "/gallery/gallery-thum-04.jpg",
		alt: "Spacious family home with green garden in a peaceful suburb",
		title: "Family Home with Garden",
		location: "101 Suburban Drive, Green Valley, Victoria Island",
		price: "₦1,750,000",
		beds: 4,
		baths: 3,
		area: "2,200 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-16.jpg",
			"/gallery/gallery-17.jpg",
			"/gallery/gallery-18.jpg",
			"/gallery/gallery-19.jpg",
			"/gallery/gallery-20.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 5,
		image: "/gallery/gallery-thum-05.jpg",
		alt: "Luxury penthouse with panoramic city skyline view and modern design",
		title: "Penthouse with City Skyline View",
		location: "202 High Rise Avenue, Uptown, Chevron",
		price: "₦3,200,000",
		beds: 3,
		baths: 3,
		area: "2,800 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-21.jpg",
			"/gallery/gallery-22.jpg",
			"/gallery/gallery-23.jpg",
			"/gallery/gallery-24.jpg",
			"/gallery/gallery-25.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-05.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-02.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-04.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-01.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-04.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-06.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
	{
		id: 6,
		image: "/gallery/gallery-thum-02.jpg",
		alt: "Modern townhouse near park with green surroundings and family-friendly amenities",
		title: "Modern Townhouse Near Park",
		location: "303 Park View Road, Greenside, Aja",
		price: "₦1,450,000",
		beds: 2,
		baths: 2,
		area: "1,100 sqft",
		type: "For Sale",
		detailImages: [
			"/gallery/gallery-26.jpg",
			"/gallery/gallery-27.jpg",
			"/gallery/gallery-28.jpg",
			"/gallery/gallery-29.jpg",
			"/gallery/gallery-30.jpg",
		],
		description:
			"Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!,This property is mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley.Located right in the heart of Upstate NYs Amish farm Country, this land is certified organic makingit extremely rare! Good road frontage on a paved county road with utilities make it an amazingsetting for your dream country getaway! If you like views, you must see this property!This propertyis mostly wooded and sits high on a hilltop overlooking the Mohawk River Valley. Located right inthe heart of Upstate NYs Amish farm Country, this land is certified organic making it extremelyrare! Good road frontage on a paved county road with utilities make it an amazing setting for yourdream country getaway! If you like views, you must see this property!",
	},
];
